#!/usr/bin/env node

var count = (process.argv[2] && parseInt(process.argv[2], 10)) || 100;
var type = process.argv[3] || 'point';
var max_radial_length = (process.argv[4] && parseFloat(process.argv[4], 10)) || 0.5;
var num_vertices = (process.argv[5] && parseInt(process.argv[2], 10)) || 12;

console.log(JSON.stringify(require('./')(count, type, max_radial_length, num_vertices)));
