#!/usr/bin/env node

var count = (process.argv[2] && parseInt(process.argv[2], 10)) || 100;
var type = process.argv[3] || 'point';
var geojsonStream = require('geojson-stream');
var geojsonRandom = require('./');

if (type === 'point-stream') {
  geojsonRandom.pointStream(count)
    .pipe(geojsonStream.stringify())
    .pipe(process.stdout);
} else {
  console.log(JSON.stringify(geojsonRandom[type](count)));
}
